### ISSUE TITLE
how to use this repo in my app ?

### ISSUE THREAD

**Issue by OdaiTu** [atwwei/ngx-dfp#1]
how to use the repo in my application ?

**Comment by OdaiTu** [comment]
i just added the code  and  the ad- unit but the ad dosent show
but when i inspect the element and see the ad i see the frame there ! but with display none ?

**Comment by atwwei** [comment]
I have also encountered this problem. Since I do not have a Google ads account, I can not test it. I guess that may be related to the delivery of Google ads !

You can see the demo here [https://github.com/atwwei/ngx-dfp-demo](https://github.com/atwwei/ngx-dfp-demo)

**Comment by OdaiTu** [comment]
@atwwei 
when i push the ad-unit to static html page it shows without problems
but when to use it with angular nothing to show
i need it so bad to work !

**Comment by atwwei** [comment]
I am very sorry! If you think there are some problems, you can modify it, just like what you want!

**Comment by atwwei** [comment]
You can view the page to learn about "setForceSafeFrame": [googletag.PubAdsService_setForceSafeFrame](https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_setForceSafeFrame).

Then you can try to modify the code like this:
```HTML
<dfp-ad [forceSafeFrame]="false" adUnit="/path-to-my/ad-unit">
    <dfp-size [width]="320" [height]="50"></dfp-size>
</dfp-ad>
```
