### ISSUE TITLE
Blank in ionic3

### ISSUE THREAD

**Issue by Supriyuadi** [atwwei/ngx-dfp#10]
Hi,

The module works fine and i dont get any error. iframe is showing, but there no content in there.
![screen shot 2018-04-09 at 18 22 21](https://user-images.githubusercontent.com/6533657/38495196-f8a29c70-3c22-11e8-9633-97b70b826244.png)

Would appreciate any help.

Thanks.

**Comment by atwwei** [comment]
No ads found, then empty dfp-ad collapsed.
