### ISSUE TITLE
How do I send bind angular variables for targeting

### ISSUE THREAD

**Issue by kartikbb** [atwwei/ngx-dfp#11]
I have following code

`<dfp-ad [forceSafeFrame]="true" [collapseIfEmpty]="true" adUnit="{{dfpLeaderboardAdUnitPath}}"
            responsive>
      <dfp-size [width]="728" [height]="90"></dfp-size>
      <dfp-targeting key="slug">
        <dfp-value>{{slugForDfpTargeting}}</dfp-value>
      </dfp-targeting>
    </dfp-ad>`

the adUnit works but the dynamic value pass for targeting does not. If I replace it with static value then it works fine.

How do we pass a dynamic value for targeting?

**Comment by atwwei** [comment]
You can try the code below.
<dfp-targeting key="slug" [value]="slugForDfpTargeting"> </dfp-targeting>

**Comment by kartikbb** [comment]
Thanks, it worked
`<dfp-ad [forceSafeFrame]="true" [collapseIfEmpty]="true" [adUni]t="dfpLeaderboardAdUnitPath" responsive> <dfp-size [width]="728" [height]="90"></dfp-size> <dfp-targeting key="slug" [value]="slugForDfpTargeting"> </dfp-ad>`
