### ISSUE TITLE
How to disable single Request

### ISSUE THREAD

**Issue by BABY-DESTINATION** [atwwei/ngx-dfp#12]
I Have the following code taken from the demo I want to disable singleRequest how can I do it
`<dfp-ad [forceSafeFrame]="true" [collapseIfEmpty]="true" adUnit="/35096353/pub-showcase" responsive">
    <dfp-size [width]="320" [height]="50"></dfp-size>
    <dfp-size [width]="728" [height]="90"></dfp-size>
    <dfp-size [width]="970" [height]="90"></dfp-size>
    <dfp-targeting key="food">
        <dfp-value>chicken</dfp-value>
        <dfp-value>meatballs</dfp-value>
        <dfp-value>ice cream</dfp-value>
    </dfp-targeting>
</dfp-ad>`

**Comment by atwwei** [comment]
If you want to enable single request mode to get multiple ads at the same time, it is not yet implemented.

**Comment by BABY-DESTINATION** [comment]
Thank you for the update, any idea when can we expect this

**Comment by atwwei** [comment]
ngx-dfp@1.2.3 [SingleRequestMode](https://github.com/atwwei/ngx-dfp/blob/a4bf853bf4db81789b13978de1519923d543580f/demo/app/app.module.ts#L16)

**Comment by BABY-DESTINATION** [comment]
thanks closing it 👍
