### ISSUE TITLE
Bind Width and Height

### ISSUE THREAD

**Issue by igorsky78** [atwwei/ngx-dfp#13]
Hello,

I'm having problem with binding width and height. 
  <dfp-ad [forceSafeFrame]="true" [collapseIfEmpty]="true" adUnit="/{{dfpNetwork}}/{{dfpAdUnit}}">
      <dfp-size [width]="dfpWidth" [height]="dfpHeight"></dfp-size>
    </dfp-ad>

The value from my dfpWidth and dfpHeight are never being picked up.

Any help would be appreciated

**Comment by atwwei** [comment]
Too little information, you can make a demo at [https://stackblitz.com](https://stackblitz.com) !
