### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by aswinsanakan** [atwwei/ngx-dfp#14]
First off, I'm running ngx-dfp in an Angular 5 application.
Is this package compatible with this version of Angular, and if so, can you help me debug this error ?

![screen shot 2018-05-18 at 2 22 04 pm](https://user-images.githubusercontent.com/23277565/40225521-e61a118a-5aa6-11e8-92fc-697afdb10f0a.png)

I've only recreated the same configurations as in the demo app. 
It seems to me that the dfp-size tag is not getting recognized. Any ideas ?

**Comment by atwwei** [comment]
Looks like you didn't import DfpModule in current NgModule !

**Comment by KumarAtFolio3** [comment]
Hello @atwwei 
I have the problem as shown in screenshot below. I am on angular 5.
![ngx-dfp-error-angular5](https://user-images.githubusercontent.com/52962423/61512961-f485fb80-aa14-11e9-8232-8e9f1e3c1784.png)

Any help with be appreciated.
Thanks.
