### ISSUE TITLE
Ionic 3 compatibility

### ISSUE THREAD

**Issue by AndreasGassmann** [atwwei/ngx-dfp#15]
I tried using your module in an Ionic 3 based project, but I get the following error:

```
Typescript Error
Cannot find name 'Router'.
node_modules/ngx-dfp/lib/directive/dfp-ad.directive.d.ts
```

`router: Router` seems to be the problem.

```
private onSameNavigation;
constructor(platformId: Object, elementRef: ElementRef, dfp: DfpService, dfpIDGenerator: DfpIDGeneratorService, dfpRefresh: DfpRefreshService, config: DfpConfig, router: Router);
ngOnInit(): void;
```

Here the versions I am using:

```
Ionic Framework: ^3.9.2
Ionic App Scripts: 3.1.5
Angular Core: 5.1.1
Angular Compiler CLI: 5.1.1
Node: 10.3.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
```

I installed and imported the angular router, which seemed to work. But because Ionic already has routing, I'm not sure if this will cause other problems. Would it be possible to remove the router dependency?

**Comment by atwwei** [comment]
You can try ngx-dfp@1.2.6. 'angular/router' is also required, and no other problems.

**Comment by AndreasGassmann** [comment]
Hi, thanks for the fix. It is working now without adding the router to my modules.
