### ISSUE TITLE
I click on the dfp ad new window does not open

### ISSUE THREAD

**Issue by ugurozcan** [atwwei/ngx-dfp#16]
<dfp-ad [forceSafeFrame]="true" [collapseIfEmpty]="true" adUnit="{{dfpHomeBanner}}">
	 <dfp-size [width]="320" [height]="142"></dfp-size>
</dfp-ad>	

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.8.1
    npm               : 5.5.1
    OS                : Windows 10

Packet versiyon : 
    "ngx-dfp": "^1.2.2",

**Comment by atwwei** [comment]
Sorry, dfp-ad only loads and refreshes ad. If the ad is rendered correctly, this may be limited by other reasons.
