### ISSUE TITLE
How to work with Video ad in DFP

### ISSUE THREAD

**Issue by BABY-DESTINATION** [atwwei/ngx-dfp#17]
Hi I am trying to integrate a video AD in DFP, how can I do it , we are using this module for displaying our banner ads

**Comment by atwwei** [comment]
Thanks for your issue, i will try to complete dfp-video for video ad in the next version.

**Comment by atwwei** [comment]
Maybe, I didn't understand exactly! What are the specific question and difficulties encountered?

**Comment by BABY-DESTINATION** [comment]
Hi I am trying to serve DFP video ads, We are already using this to serve our banner ads but in case of video ads it is not so as the video player will request ads. The difficulty is that at moment there is no straightforward way where you can place the video ad tags and be done. I want to be something simple where I don't have worrry about integrating IMA integration and all . Hope it helps

**Comment by atwwei** [comment]
I released the beta version ngx-dfp@beta, you can try it like the [demo](https://github.com/atwwei/ngx-dfp/blob/bf1032c792474f8c0d132449f24942d0cee1ec0d/demo/app/page/page.component.html#L44).

Hope it helps!

**Comment by BABY-DESTINATION** [comment]
Cool Thanks I will try it out and let you know 👍
