### ISSUE TITLE
Angular 6 ngx-dfp

### ISSUE THREAD

**Issue by igorsky78** [atwwei/ngx-dfp#18]
Hello 

When i try to add ngx-dfp to my project and build in for production.
I get following error:
`EXEC(0,0): Error : The structure of the program changed during codegen.
Child
    Hash: a09daa5209a4c026c2c0
    Time: 15684ms
    Built at: 06/18/2018 3:57:44 PM
     1 asset
    Entrypoint main-server = main-server.js
`
If i remove ngx-dfp reference, my project build with no errors.

Also the Ad is working in development environment.

**Comment by atwwei** [comment]
Thanks for your issue, but i still can't judge. Can you show me the dependencies and other useful configurations.

**Comment by igorsky78** [comment]
Here is my configuration.

Package.json - [package.json.txt](https://github.com/atwwei/ngx-dfp/files/2115881/package.json.txt)
webpack.config.js - [webpack.config.js.txt](https://github.com/atwwei/ngx-dfp/files/2115904/webpack.config.js.txt)

I have added code below to my app.module.ts
` DfpModule.forRoot({
      idleLoad: true,
      singleRequestMode: true,
      onSameNavigation: 'refresh'
    })`

This is my AdComponent.html
`<section class="promoArea">`
`  <div [innerHtml]="promo | safeHtml"></div>  `
 ` <div *ngIf="hasAd" class="ad">`
   ` <dfp-ad [forceSafeFrame]="true" [collapseIfEmpty]="true" adUnit="/{{dfpNetwork}}/{{dfpAdUnit}}">`
   `   <dfp-size [width]="320" [height]="50"></dfp-size>`
  `    <dfp-size [width]="728" [height]="90"></dfp-size>`
   ` </dfp-ad>`
  `</div>`
`</section>`

**Comment by igorsky78** [comment]
Any ideas on why i'm getting error during production build?

**Comment by atwwei** [comment]
Can you provide a simple demo to detect problems in detail?
