### ISSUE TITLE
Multiple Ad sizes per AdUnit

### ISSUE THREAD

**Issue by liviogottardi** [atwwei/ngx-dfp#19]
As I've seen currently while working with multiple ad sizes in responsive mode the biggest possible ad size is taken, regarding the available with.

Is it possible to filter the sizes and remove only the to big ad sizes? So multiple ad sizes per AdUnit are requested?

**Comment by atwwei** [comment]
Sorry, it's just a simplified version. Like you said, just choose the biggest.
 I will try to improve it later.

Tanks for your issue!

**Comment by atwwei** [comment]
In the latest version, you can try the dfp-response.

Hope it helps!
