### ISSUE TITLE
Ad unit did not render

### ISSUE THREAD

**Issue by liviogottardi** [atwwei/ngx-dfp#20]
It seems to be that the whole configuration is correct and the ad is requested in DFP but unfortunately not rendered. 
The DFP debug consoles output (Screenshot): "Ad unit did not render".

Do you have any idea?

<img width="556" alt="screen shot 2018-06-20 at 06 23 07" src="https://user-images.githubusercontent.com/4557799/41652320-03eff288-7483-11e8-8c17-3b4fedf77637.png">

**Comment by atwwei** [comment]
If the problem persists, please provide a link to the preview page!

**Comment by atwwei** [comment]
May be caused by the bug: #25 (request safeframe ads only)
