### ISSUE TITLE
ngx-dfp RxJS bundle size

### ISSUE THREAD

**Issue by wmaurer** [atwwei/ngx-dfp#28]
**Describe the bug**
When using ngx-dfp, the bundle size of a Angular CLI bootstrapped app is much larger than expected.
All the RxJS operators are imported.

**To Reproduce**
1.  ng new ...
2. install `ngx-dfp` and import `DfpModule`
3. Analyze bundle size with `webpack-bundle-analyzer`.

**Expected behavior**
Only the RxJS operators used by `ngx-dfp` should be in the final bundle.

I have spent many hours trying to work out why this is the case, and believe it is because of the way ngx-dfp  is compiled and distributed. I have made some changes to `ngx-dfp` to allow it to be compiled with [ng-packgr](https://github.com/dherges/ng-packagr). `ng-packgr` is the preferred way of compiling Angular libraries by the Angular team. In fact it's used by the Angular CLI.

The good news, I was able to reduce the bundle size significantly, so only the RxJS operators used by `ngx-dfp` are included in the final production bundle.

Unfortunately the changes also involved some changes to the source code, mostly to do with the locations of files and where they got imported from. I can't really explain why I had to make some of the changes. It simply didn't compile or work without these changes.

Anyway, I'll submit a PR (tomorrow) and @atwwei can you please give some feedback about what you think.

**Comment by atwwei** [comment]
Thanks for your issue and pull !
