### ISSUE TITLE
Universal plans?

### ISSUE THREAD

**Issue by randomparanoia** [atwwei/ngx-dfp#3]
Hello, dropping by to know if there are any plans to integrate your package with univeral? I was able to workaround with isPlatformBrowser(), but still have to modify your service to verify for window undefined. thanks

**Comment by atwwei** [comment]
Because no relevant experience, I hope you can provide the environment,related tools and configuration. Then i will try it to help you.

Thanks for your issue !

**Comment by randomparanoia** [comment]
@atwwei I am using [https://github.com/angular/universal-starter/](url). Its based on angular/cli so might be easier to debug and test out of the box.

Thanks!

**Comment by atwwei** [comment]
Now just client-side rendering, and then the other server-side codes should work fine!

**Comment by randomparanoia** [comment]
Seems good! closing
Thanks :)
