### ISSUE TITLE
Error: Cannot find module 'ngx-dfp/lib/directive/dfp-ad.directive'

### ISSUE THREAD

**Issue by kartikbb** [atwwei/ngx-dfp#30]
A new release today morning has broken our SSR app. The error is

Error: Cannot find module 'ngx-dfp/lib/directive/dfp-ad.directive'

**Comment by atwwei** [comment]
ngx-dfp@1.5.0?

**Comment by atwwei** [comment]
I just test SSR with ngx-dfp@1.5.0, it works well!

**Comment by randomparanoia** [comment]
in my case -> 

ERROR in ./node_modules/ngx-dfp/fesm5/ngx-dfp.js
Module not found: Error: Can't resolve '@alugha/ima'

**Comment by atwwei** [comment]
Just install @alugha/ima

**Comment by randomparanoia** [comment]
just did :)
