### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by abyrne85** [atwwei/ngx-dfp#33]
Is Lazy Loading a possibility with this package?

**Comment by atwwei** [comment]
Nothing is impossible, but no need to do so!

**Comment by abyrne85** [comment]
Just wondering why you don't think it is necessary.  Wouldn't it be better to not load all the ads on a page at once?  It would increase page load time and give improper stats regarding ads view-ability.  I think adding enableLazyLoad to the service ts file would be useful. 




    pubads.enableLazyLoad({

      fetchMarginPercent: 200,  // Fetch slots within 2 viewports.

      renderMarginPercent: 100,  // Render slots within 1 viewports.

      mobileScaling: 2.0  // Double the above values on mobile.

    });`

**Comment by atwwei** [comment]
You can use googletag.cmd before dfp works:
```
googletag.cmd.push(function() {
      googletag.pubads().enableLazyLoad({
        fetchMarginPercent: 200,
        renderMarginPercent: 100,
        mobileScaling: 2.0
      });
});
```
