### ISSUE TITLE
Callback when ad is rendered not firing

### ISSUE THREAD

**Issue by sir-captainmorgan21** [atwwei/ngx-dfp#34]
**Describe the bug**
The renderEnded event isn't emitted when the ad finishes rendering. We get the init event, but not the renderEnded event. I checked your demo where you are logging out the event, and the same thing applies there.

**To Reproduce**
Go to your demo and open up the console and watch the logs. Only the init event is logged.

**Additional context**
@atwwei when does the slot render event get emitted? We are trying to wait for the ad to render before we show the rest of our listings, but the renderEnded event never gets called. We see the init event, but not the renderEnded event.

**Comment by atwwei** [comment]
Fixed in ngx-dfp@1.6.2.

Thanks for your issue!

**Comment by sir-captainmorgan21** [comment]
@atwwei do you handle the case where the ad actually does not render? (timeouts, errors, etc.)?

**Comment by atwwei** [comment]
@sir-captainmorgan21  Just handle some events extended from [googletag.events.Event](https://developers.google.com/doubleclick-gpt/reference#googletageventsevent).

**Comment by sir-captainmorgan21** [comment]
@atwwei Not sure how I would handle them. Is the `dfp-ad` component surfacing every event that the ad emits?
