### ISSUE TITLE
Can't resolve '@alugha/ima'

### ISSUE THREAD

**Issue by dylanvdmerwe** [atwwei/ngx-dfp#35]
**Describe the bug**
Updating to angular 7.2.0 and receive the following error when running `ng build`. 

```
ERROR in ./node_modules/ngx-dfp/fesm5/ngx-dfp.js
Module not found: Error: Can't resolve '@alugha/ima' in 'C:\Projects\site-app\node_modules\ngx-dfp\fesm5'
```

**To Reproduce**
Add `ngx-dfp` to a starter angular project and try build.

**Comment by atwwei** [comment]
Fixed in ngx-dfp@1.6.2.

Thanks for your issue!
