### ISSUE TITLE
Sourcecode and changelog for latest releases

### ISSUE THREAD

**Issue by wmaurer** [atwwei/ngx-dfp#38]
Hello @atwwei 

I've just noticed there's a new version 1.6.2 available on NPM.
I don't see any commits related to this release in this repository.
It would be very useful to know what has changed. Would you be able to publish the latest source code and maybe also summarise the changes in a CHANGELOG?
Think this would be very valuable to the consumers of this library.

Thank you, and thanks for all your effort in building ngx-dfp.

Regards
Wayne

**Comment by atwwei** [comment]
Just fix the bug #34  .  I'll push the commits later.

Thanks for your issue!
