### ISSUE TITLE
Support Out of page

### ISSUE THREAD

**Issue by leandroromeroramirez** [atwwei/ngx-dfp#39]
Hi,

I do not find out how to use the components with a type of **OutofPage** advertising, which can be seen in this url https://support.google.com/admanager/answer/6088046?hl=en 

does support exist for this case?

**Comment by atwwei** [comment]
You can try the code bellow:

```
<dfp-ad adUnit="????">
  <dfp-size [width]="1" [height]="1"></dfp-size>
</dfp-ad>
```

**Comment by leandroromeroramirez** [comment]
Hi tks for you comment,
See this code generate to ad-manger 

<script>
  googletag.cmd.push(function() {
    googletag.defineOutOfPageSlot('/····/FUERA_DE_PAGINA', 'div-gpt-ad-1551749245713-0').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.pubads().collapseEmptyDivs();
    googletag.enableServices();
  });
</script>

not exist size and see this function "googletag.defineOutOfPageSlot" diferent to googletag.defineSlot

**Comment by atwwei** [comment]
You can try the ngx-dfp@beta :

```
<dfp-ad adUnit="????"></dfp-ad>
```

Then tell me if it works well!
