### ISSUE TITLE
DFP Ad's Slot Refresh Error

### ISSUE THREAD

**Issue by ksaadST** [atwwei/ngx-dfp#40]
I have integrated this modules successfully but i am getting slot refresh error.<y project is on angular 5.2.0.Please find attachment for reference.
<img width="601" alt="Screenshot 2019-07-11 at 8 39 57 PM" src="https://user-images.githubusercontent.com/1706239/61065037-5397af00-a41c-11e9-832e-f92c3974850d.png">

**Comment by KumarAtFolio3** [comment]
Hello Guys,
I have the same error as shown in the screenshot below. My project is on Angular 5.

![ngx-dfp-error-angular5](https://user-images.githubusercontent.com/52962423/61512277-cf908900-aa12-11e9-92d0-a315c38591c0.png)

Any help will be appreciated.
Thanks.

**Comment by atwwei** [comment]
@KumarAtFolio3 The latest version is based on Angular6 and rxjs6, you can try a low version like ngx-dfp@1.3.2-rxjs5

**Comment by KumarAtFolio3** [comment]
> @KumarAtFolio3 The latest version is based on Angular6 and rxjs6, you can try a low version like ngx-dfp@1.3.2-rxjs5

Thanks a lot @atwwei 
It worked for me.
