### ISSUE TITLE
Not working on Angular 9

### ISSUE THREAD

**Issue by lunar-safari** [atwwei/ngx-dfp#43]
Banner ads aren't loading using this on Angular 9.

The authors stackblitz example has stopped working too;
https://stackblitz.com/edit/angular-fftqvj?file=src%2Fapp%2Fpage2%2Fpage2.component.html

Any one using it successfully?

**Comment by atwwei** [comment]
@lunar-safari  No problem found! Any error messages in the browser console?

**Comment by lunar-safari** [comment]
> @lunar-safari No problem found! Any error messages in the browser console?

OK, could be something my end. Thanks for the reply.
Are you seeing ads on the StackBlitz link?

**Comment by atwwei** [comment]
> > @lunar-safari No problem found! Any error messages in the browser console?
> 
> OK, could be something my end. Thanks for the reply.
> Are you seeing ads on the StackBlitz link?

Yes, I can see the ads on the StackBlitz link。
