### ISSUE TITLE
ngx-dfp responsive issue

### ISSUE THREAD

**Issue by udayannadi** [atwwei/ngx-dfp#44]
@atwwei @DanielGBullido @wmaurer 
 I have used following code to display adds in my angular application, but following code working fine in all **web** **browsers** and even **android** **mobiles**.

But getting adds displaying in inconsistent in **iPhone** and **opera** browsers responsive mode. some ads displaying in **iPhone** and some ads are not displaying.

Please help on my issue.

Is there any wrong responsive configuration  code in following? 
Is there responsive configuration missed for **iPhone** Responsiveness?
"<dfp-ad adUnit="/21887107778/div-gpt-ad-1595615839597-0" responsive>
              <dfp-size [width]="255" [height]="240"></dfp-size>
              <dfp-size [width]="160" [height]="600"></dfp-size>
              <dfp-size [width]="200" [height]="200"></dfp-size>
              <dfp-size [width]="240" [height]="400"></dfp-size>
              <dfp-size [width]="250" [height]="360"></dfp-size>
              <dfp-size [width]="250" [height]="250"></dfp-size>
              <dfp-responsive [adSizes]="[[160,600],[200,200],[240,400],[250,360],[255,240],[250,250]]"></dfp-responsive> 
</dfp-ad>"
 

Regards,
Uday A

**Comment by atwwei** [comment]
@udayannadi The `dfp-responsive` is actually a simplified version and may be different from what you expect.

**Comment by udayannadi** [comment]
@atwwei 

Thanks for the response, we have been facing this issue only with the **IPhone** mobile browser (Safari). So is there any compatibility issues for this plugin with the **IPhone** browser (Safari)? This is a high priority thing and client is waiting for the fix for this. Please help me on this.

If we change safari browser settings in **IPhone**  settings -> safari browser -> turn off **Prevent cross-site tracking.**    
Then we can see ads.

 But if turn on **Prevent cross-site tracking** we can't see ads in **IPhone**.

Please help me on this ASAP.

**Comment by atwwei** [comment]
@udayannadi 
Maybe this can help you : https://developers.google.com/doubleclick-gpt/samples/configure-privacy ~ Restricted data processing
