### ISSUE TITLE
Reload config based on user cookie preference

### ISSUE THREAD

**Issue by newcreativegamer** [atwwei/ngx-dfp#45]
Hi,

I would greatly appreciate fast feedback on this one. I want to change the personalizedAds from true to false at runtime when the user accepts tracking cookies. What is the best way of changing the config at runtime?

Thanks,
Alan.

**Comment by atwwei** [comment]
@newcreativegamer 
You can try to change the configuration using googletag.cmd as follows:
```
googletag.cmd.push(() => {
	// Mark ad requests to request non-personalized ads.
	googletag.pubads().setRequestNonPersonalizedAds(1);
	// Refresh ads when necessary
	googletag.pubads().refresh();
});
```

**Comment by newcreativegamer** [comment]
Thanks @atwwei! That's exactly what I was looking for.
