### ISSUE TITLE
Video ads Source field

### ISSUE THREAD

**Issue by sangeethkumarsg** [atwwei/ngx-dfp#46]
Hi I saw your demo for video ads. But what should I pass in the source path for video ads. All I got is an adTag.  Can you please explain?

  ```
  <dfp-video width="640" height="480" [adActions]="adInput" (adEvents)="adEvent($event)" adTag="https://pubads.g.doubleclick.net/gampad/ads?iu=/[XXXXID]/[XXXAdUnit]&tfcd=0&npa=0&sz=320x480%7C480x320%7C1024x768%7C768x1024&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=">
        <video class="video-js" controls preload="auto" data-setup="{}" poster="https://google-developers.appspot.com/interactive-media-ads/images/vsi_poster.jpg">
            <source src="//s0.2mdn.net/4253510/google_ddm_animation_480P.mp4">
        </video>
        <div class="ad-container" (click)="adInput.emit('play')"></div>
    </dfp-video>
```

Sorry I am new to integration of ads. Please help me.

**Comment by atwwei** [comment]
@sangeethkumarsg [IMA sample tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags)

**Comment by sangeethkumarsg** [comment]
@atwwei ,
Can you please a sample code with your plugin implementation? The above mentioned sample code have hard coded video source. I am confused about how do the auto ad placement by DFP is possible with your component?

**Comment by atwwei** [comment]
Interactive Media Ads SDKs


> @atwwei ,
> Can you please a sample code with your plugin implementation? The above mentioned sample code have hard coded video source. I am confused about how do the auto ad placement by DFP is possible with your component?

@sangeethkumarsg The video tag is the content of the web page, not from DFP. The component just a simple usage of  [Interactive Media Ads SDKs](https://developers.google.com/interactive-media-ads)。
