### ISSUE TITLE
How to set globalTargeting in DfpService

### ISSUE THREAD

**Issue by kohatang** [atwwei/ngx-dfp#5]
```
import {DfpService} from 'ngx-dfp/lib/service';
DfpService.globalTargeting = {key: 'value'};

Property 'globalTargeting' does not exist on type 'typeof DfpService'.
```

So, How to set globalTargeing from my module??

**Comment by atwwei** [comment]
ngx-dfp@1.1.9 is ready for you ! Now you can config this , like  [Demo](https://github.com/atwwei/ngx-dfp#dfpconfig) .   

 [DfpConfig](https://github.com/atwwei/ngx-dfp/blob/master/src/class/dfp-config.class.ts)  source here!

**Comment by kohatang** [comment]
Thank you for upgrading. It is working very well.
