### ISSUE TITLE
Responsive adds

### ISSUE THREAD

**Issue by kjimenezdev** [atwwei/ngx-dfp#6]
Hi, is there a way to change the style of the tags generated by DFP so it's possible to resize de add banner?  The issue I'm having is that when the web app resizes to a smaller device  <=768 the banner does not resizes automatically and I can't edit the style as it is created after the view appears.

Thanks in advance.

**Comment by atwwei** [comment]
So sorry, i just see your issue.
In fact, dfp-size is probably what you want. The width of dfp-size is the min-width for responsive refresh.

**Comment by ljnocca** [comment]
@kjimenezdev - were you able to find a solution on dynamic resizing? I'm also trying to solve this issue using Angular 4.

**Comment by kjimenezdev** [comment]
Hi, It's possible if you load more images as dfp creatives on dfp admin panel. If you test your site on a smaller size (instead of dragging the browser responsive mode it until it gets into a smaller resolution) automatically dfp will provide a smaller size for the banner.

**Comment by atwwei** [comment]
[dfp-responsive](https://github.com/atwwei/ngx-dfp/blob/8d03cca5b54a66b53f9c992e27a9a81728911fb6/demo/app/page/page.component.html#L30)
