### ISSUE TITLE
element in DOM?

### ISSUE THREAD

**Issue by Frrede** [atwwei/ngx-dfp#7]
First nice plugin! Thanks for that! :)
Do you ensure, that the element is already in the DOM when calling `googletag.display(id)`?
Because I guess it's doing a `document.getElementByID` and in`AfterViewInit` when you call it it's not guaranteed that the element is already attached to the DOM isn't it?
Isn't it maybe a raise condition problem?
Sorry if I'm missing something...

**Comment by atwwei** [comment]
Element ID was firstly created in DfpAdDirective.ngOnInit()!

**Comment by Frrede** [comment]
Wouldn't it be safer to take `afterViewInit` because in`onInit` I think it might not always be given that the element is already in the dom...
