### ISSUE TITLE
Callback when ad is loaded

### ISSUE THREAD

**Issue by abyrne85** [atwwei/ngx-dfp#8]
Would it be possible to include some usable data in the afterRefresh event?  ie size of ad returned and whether or not it's empty

**Comment by atwwei** [comment]
ngx-dfp@1.2.1 [SlotRenderEndedEvent](https://github.com/atwwei/ngx-dfp/blob/7a33661d42f3cda2b5d73396230869c83a46872d/demo/app/app.component.ts#L13)

**Comment by abyrne85** [comment]
This is great.  Thank you.

**Comment by sir-captainmorgan21** [comment]
@atwwei when does the slot render event get emitted? We are trying to wait for the ad to render before we show the rest of our listings, but the renderEnded event never gets called. We see the init event, but not the renderEnded event.
